# -- REQUIRED -- #

# Proxmox API host domain or IP address. Needs to be accessible with https.
pm_host = "pve1.lan:8006"
# Proxmox API username. When using API key, the format would be e.g. 'packer@pve!packer'.
pm_api_username = "packer@pve!packer"
# Proxmox API key. Either this or pm_api_password is required.
pm_api_key = "0a1b2c3d-4e5f-678a-9b0c1-d2e3f4a5b6c7"
# Proxmox API password. Either this or pm_api_key is required.
pm_api_password = null
# The target node the template will be built on.
pm_node = "pve1"
# ssh key of default admin user
ssh_key = "ssh-dsa ..."

# -- OPTIONAL -- #

# How long to wait for an SSH connection before cancelling (without QEMU guest agent, this is how long the build can take)
ssh_timeout = "15m"
# Whether to skip validating the API host TLS certificate.
pm_skip_tls_verify = true
# If you have a local ISO, specify it here.
# iso_file = "local:iso/debian-11.2.0-amd64-netinst.iso"
# If you have a local ISO, specify its checksum here.
# iso_checksum = "c685b85cf9f248633ba3cd2b9f9e781fa03225587e0c332aef2063f6877a1f0622f56d44cf0690087b0ca36883147ecb5593e3da6f965968402cdbdf12f6dd74"
# When not specifying a local ISO, it will be downloaded from official sources.
# The target storage needs to be specified here. Packer user needs 'Datastore.AllocateTemplate' privileges.
iso_storage_pool = "local"
# If you don't have a local ISO, make sure the debian version
# specified below is the current netinstaller one.
os_version = "11.7.0"
# Whether to attach a cloud-init CDROM drive to the built template.
cloud_init = true
# The storage pool for the cloud-init CDROM.
cloud_init_pool = "local-lvm"
# The VM ID used for the build VM and the built template.
vm_id = 1000
# Number of CPU cores for the VM.
cpu_cores = 2
# CPU type to emulate. Best performance: 'host'.
cpu_type = "host"
# Megabytes of memory to associate with the VM.
memory = "2048"
# Choose the machine BIOS: 'ovmf', 'seabios'
bios = "seabios"
# Choose the machine type: 'i440fx', 'q35'
machine = "i440fx"
# The SCSI controller model to emulate: lsi, lsi53c810, virtio-scsi-pci, virtio-scsi-single, megasas, pvscsi
scsi_controller = "virtio-scsi-single"
# The storage pool for the default disk.
disk_pool = "local-lvm"
# The storage pool type for the default disk.
disk_pool_type = "lvm-thin"
# The disk size of the default disk.
disk_size = "5G"
# How to cache operations to the default disk. Can be 'none', 'writethrough', 'writeback', 'unsafe' or 'directsync'
disk_cache_mode = "none"
# The format of the default disk: 'raw', 'cow', 'qcow', 'qed', 'qcow2', 'vmdk', 'cloop'
disk_format = "raw"
# Create one I/O thread per storage controller, rather than a single thread for all I/O.
# Requires virtio-scsi-single controller and a scsi or virtio disk
disk_io_thread = false
# The type of the default disk: 'scsi', 'sata', 'virtio', 'ide'.
disk_type = "virtio"
# The bridge the default NIC is attached to.
nic_bridge = "vmbr0"
# Whether to enable the PVE firewall for the default NIC.
nic_firewall = false
# The model of the default NIC.
nic_model = "virtio"
# The VLAN tag the default bridge uses. Leave empty for untagged
nic_vlan = null
# Number of packet queues to be used on the default NIC. Requires virtio network adapter.
nic_queues = 0
# The VGA type: cirrus, none, qxl, qxl2, qxl3, qxl4, serial0, serial1, serial2, serial3, std, virtio, vmware
vga_type = "serial0"
# VGA memory in MiB. Note: this is superfluous when using a serial console.
vga_memory = 64
# The default admin username.
default_username = "debian"
# The system language
language = "en"
# The system country
country = "UK"
# The system timezone
timezone = "Europe/London"
# The system kemap
keymap = "us"
# A root password to use, best to leave it autogenerated by not specifying it
root_password = "hunter1"
# Whether to enable Bullseye backports repository
# (cloud-init v22.2 fixes a bug with static routes for single hosts)
# https://github.com/canonical/cloud-init/commit/9a258eebd96aa5ad4486dba1fe86bea5bcf00c2f
backports = true
